### PR TITLE
Math Magicians: refactor with hooks

### PR DESCRIPTION
**Pull request by arthurborgesdev**
# In this Pull Request I implemented:

- Refactor Calculator.js class to use Hooks instead and converted it into a functional component.
- Fix the problem of division by 0 showing an error message in the display.

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
Hello @arthurborgesdev 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Linter is correct
- Descriptive README, PR summary, headline, and commit messages
- Well done refactoring the code from the class-based component into the functional component using hooks

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️

_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by acushlakoncept — COMMENTED** [review]
Hello @arthurborgesdev 👋,

_This is an additional review as a result of the second opinion request._

I am so sorry, you're encountering a lot of errors while refactoring class components into functional components. It's okay to have bugs.

However, I noticed in the commits after the code review, I did not experience this bug again meaning you may have fixed it, which is good.

So, you should go ahead and ask for another CR, and don't forget to remove all `console.logs`

Keep rocking 🚀!

**Comment by arthurborgesdev** [comment]
> Hello @arthurborgesdev ,
> 
> _This is an additional review as a result of the second opinion request._
> 
> I am so sorry, you're encountering a lot of errors while refactoring class components into functional components. It's okay to have bugs.
> 
> However, I noticed in the commits after the code review, I did not experience this bug again meaning you may have fixed it, which is good.
> 
> So, you should go ahead and ask for another CR, and don't forget to remove all `console.logs`
> 
> Keep rocking !

The problems/bugs weren't in the refactor of class components into functional components. They were in the "calculate.js" file provided by Microverse. Anyway, I guess I fixed everything right now.

**Review by vichuge — APPROVED** [review]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

InbornCandidHornet-size_restricted

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
